services:
  app.datetime_controller:
    class: AppBundle\Controller\DateTimeController
    arguments:
      - '@templating'
      - '@app.service.datetime'

  app.service.datetime:
    class: AppBundle\Service\DateProvider
